# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Default'
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/postgres/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/postgres/**'
        #tags: '$(Build.BuildId)' # string. Optional. Use when command = build || command = push || command = buildAndPush. Tags. Default: $(Build.BuildId).
        #arguments: # string. Optional. Use when command != login && command != logout && command != buildAndPush. Arguments. 
        #addPipelineData: true # boolean. Add Pipeline metadata to image(s). Default: true.
        #addBaseImageData: true # boolean. Add base image metadata to image(s). Default: true.
        #container: # string. Optional. Use when command = start || command = stop. Container.