# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      displayName: Download config-prod.yaml
      name: configProd
      inputs:
        secureFile: 'config-prod.yaml'
    - task: CopyFiles@2
      displayName: Copy config-prod.yaml to source directory
      inputs:
        Contents: '$(caCertificate.secureFilePath)'
        TargetFolder: '$(Build.SourcesDirectory)' 
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/deployments-prod/api/Dockerfile'
        tags: |
          $(tag)
