version: '3.8'
services:
  if-i-am-gone-web-backend-api--dev:
    container_name: if-i-am-gone-web-backend-api--dev
    build:
      context: "../"
      dockerfile: deployments-dev/api/Dockerfile
    environment:
      - CONFIG_FILE_NAME=config-dev
      - CONFIG_FILE_TYPE=yaml
      - CONFIG_FILE_PATH=.
    ports:
      - '5501:8080'
    volumes:
      - ../:/go/src/if-i-am-gone-web-backend

  if-i-am-gone-web-backend-pg--dev:
    container_name: if-i-am-gone-web-backend-pg--dev
    build:
      context: "./postgres"
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=IFIAMGONE
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6501:5432'
    volumes: 
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql